version: "2.2.1"

volumes: 
  metadata_data: 
    driver_opts: 
      type: none 
      o: bind 
      device: ${metadata_data_folder} 
  middle_var: 
    driver_opts: 
      type: none 
      o: bind 
      device: ${middle_var_folder} 
  historical_var: 
    driver_opts: 
      type: none 
      o: bind 
      device: ${historical_var_folder}
  broker_var: 
    driver_opts: 
      type: none 
      o: bind 
      device: ${broker_var_folder} 
  coordinator_var: 
    driver_opts: 
      type: none 
      o: bind 
      device: ${coordinator_var_folder} 
  router_var: 
    driver_opts: 
      type: none 
      o: bind 
      device: ${router_var_folder} 
  druid_shared: 
    driver_opts: 
      type: none 
      o: bind 
      device: ${druid_shared_folder} 
  grafana_storage: 
    driver_opts:
      type: none 
      o: bind
      device: ${grafana_storage_folder}


services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - metadata_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_USER}
    env_file:
      - .env

  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    environment:
      - GF_INSTALL_PLUGINS=grafadruid-druid-datasource
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    env_file:
      - .env

  # Need 3.5 or later for container nodes
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5.10
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1

  coordinator:
    image: apache/druid:31.0.1
    container_name: coordinator
    volumes:
      - druid_shared:/opt/shared
      - coordinator_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
    ports:
      - "8081:8081"
    command:
      - coordinator
    env_file:
      - .env

  broker:
    image: apache/druid:31.0.1
    container_name: broker
    volumes:
      - broker_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - .env

  historical:
    image: apache/druid:31.0.1
    container_name: historical
    volumes:
      - druid_shared:/opt/shared
      - historical_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - .env

  middlemanager:
    image: apache/druid:31.0.1
    container_name: middlemanager
    volumes:
      - druid_shared:/opt/shared
      - middle_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8091:8091"
      - "8100-8105:8100-8105"
    command:
      - middleManager
    env_file:
      - .env

  router:
    image: apache/druid:31.0.1
    container_name: router
    volumes:
      - router_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - .env